# å‚è€ƒï¼šhttps://vuepress-theme-reco.recoluan.com/views/other/github-actions.html
name: Deploy GitHub Pages

# è§¦å‘æ¡ä»¶ï¼šåœ¨ push åˆ° release- å¼€å¤´çš„åˆ†æ”¯å
on:
  push:
    branches:
      - 'release-**'
      - '!releases-**-alpha'

# ä»»åŠ¡
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        # see: https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§
        run: npm install && npm run build

      - name: Deploy to GitHub Pages ğŸš€
        # see: https://github.com/marketplace/actions/deploy-to-github-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_VUEPRESS_NEXT }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist